name: Sync, Build, and Deploy Strudel

on:
  schedule:
    - cron: '0 0 * * 0' # Runs automatically every Sunday at midnight
  workflow_dispatch: # Allows you to manually trigger the build

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Strudel from Codeberg
        run: |
          git clone --depth 1 https://codeberg.org/uzu/strudel.git .
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install and Build Strudel
        run: |
          pnpm i
          pnpm run build
          
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
